/*
Copyright 2011 Google Inc. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package org.webtestingexplorer.testcase;

import org.webtestingexplorer.config.WebElementSelectorRegistry;

/**
 * Holds all the state and configuration information necessary to re-run a
 * test case in the way that it was generated by the explorer. This requires capturing
 * certain pieces from {@link org.webtestingexplorer.config.WebTestingConfig}
 * and the global registries.
 * 
 * @author scott.d.mcmaster@gmail.com (Scott McMaster)
 */
public class TestCaseConfig {

  private WebElementSelectorRegistry selectorRegistry;
  
  public TestCaseConfig(WebElementSelectorRegistry selectorRegistry) {
    this.selectorRegistry = selectorRegistry;
  }
  
  public WebElementSelectorRegistry getSelectorRegistry() {
    return selectorRegistry;
  }
}
